config/routes.rb
BcwRails::Application.routes.draw do
  get "events/index"

  get "home/index"

  root :to => "home#index"


  # Events
  resources :events, :path => "/:city_seo_string-bridal-shows"

  # Vendor Catalog

  #patterns
  page = /\d+/
  cat_seo_array = []
  begin
    Category.all_cached.each do |category|
      cat_seo_array << category.seo_string_actor_name_plural
    end
  rescue
    Rails.logger.error "category routes broken"
  end
  category = Regexp.new("(#{cat_seo_array.join('|')})")

  match '/:city_seo_string-wedding-vendors' => 'catalog#vendors', :as => 'vendors_landing', :event_type => 'weddings', :nav => 'vendors'
  match '/biz/:seo_string/:id(/:tab)(/:page)' => 'catalog#storefront', :as => 'vendor_storefront', :constraints => {:page => page}, :event_type => "weddings", :nav => "vendors"
  match '/c/:category/:location(/:page)' => 'catalog#list', :as => 'vendor_catalog', :constraints => {:page => page, :category => category}, :event_type => "weddings", :nav => "vendors"
  match '/vendors(/:location)', :to => "catalog#vendors", :as => 'vendor_landing', :event_type => "weddings", :nav => "vendors"


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :get_location
  before_filter :prepare_sidebar


  def get_location
    @bcw_city_slug = request.domain.gsub('thebest', '').gsub('best','').gsub('weddings','').gsub('wedding','').gsub('.com','')
    @bcw_city_slug = 'dc'
    @bcw_city = BcwConstants::Cities.find_city_by_url_slug(@bcw_city_slug)

    #if session[:current_location].blank? || session[:current_location] != @bcw_city_slug || session[:breadcrumb_location].blank?
      begin
        results = WeddingWire::Api::Catalog.region_fetch(@bcw_city_slug)
        session[:current_location] = @bcw_city_slug
        session[:current_region] = results[:region_code]
        session[:breadcrumb_location] = @bcw_city[:name]
      rescue Exception => ae
        session[:current_location] = nil
        session[:current_region] = nil
        session[:current_region] = nil
      end
    #end
  end

  def prepare_sidebar
    @sidebar_events = WeddingWire::Api::Catalog.events_fetch(session[:current_region], nil, 1, {:types => [{:api_string => "bridalshow"}]})
    @sidebar_events = @sidebar_events[:events]
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @page = (params[:page].present?)?params[:page] : 1
    @events = WeddingWire::Api::Catalog.events_fetch(session[:current_region], nil, 1, {:types => [{:api_string => "bridalshow"}]})
    @max_page = @events[:max_pages]
    @events = @events[:events]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @categories = Category.where(:active => true)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title, options={})
    content_for(:title, page_title.to_s)
    return content_tag(:h1, page_title, options)
  end

  def meta_title(meta_title, options={})
    content_for(:meta_title, meta_title.to_s)
    return content_tag(:meta, meta_title, options)
  end

  def meta_description(meta_description, options={})
    content_for(:meta_description, meta_description.to_s)
    return content_tag(:meta, meta_description, options)
  end

  def meta_keywords(meta_keywords, options={})
    content_for(:meta_keywords, meta_keywords.to_s)
    return content_tag(:meta, meta_keywords, options)
  end

  def is_active?(page_name)
    true if params[:action] == page_name
  end

  def city_name_pretty
    @bcw_city[:name]
  end

  def city_name_short_pretty
    @bcw_city[:name_short]
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_event_tile.html.erb
<div class="event-tile">
  <div class="event-date-container">
    <div class="month"><%= event.start_date.strftime("%b") %></div>
    <div class="day"><%= event.start_date.strftime("%-1d") %></div>
  </div>
  <div class="event-description">
    <div class="event-title"><%= link_to event.title, "#" %></div>
    <div class="event-host"><span class="light">Hosted By:</span> <%= event.vendor.name %></div>
    <div class="event-host"><span class="light">Event Type:</span></div>
  </div>

  <div style="clear:both"></div>
</div>

app/views/events/_filter_sidebar.html.erb
<div class="event-filter-sidebar">
  <div class="bcw-section-header">Events</div>

  <div class="event-filters">
    <div class="filter">All</div>
    <div class="filter">Bridal Show</div>
    <div class="filter">Trunk Show</div>
    <div class="filter">Other</div>
  </div>

  <div class="event-filters">
    <div class="filter-header">Date of Event</div>
    <div class="filter">30 Days</div>
    <div class="filter">3 Months</div>
    <div class="filter">6 Months</div>
  </div>
</div>

app/views/events/index.html.erb
<div class="bcw-breadcrumb"><%= link_to "home", root_path %> > <%= link_to "events", events_path %></div>
<div class="bcw-left-pane">

  <div style="clear:both"></div>

  <%= render 'filter_sidebar' %>

  <div class="bcw-core-middle events-list-container">
    <div class="bcw-section-header">Upcoming <%= city_name_pretty %> Bridal Shows and Events</div>

    <div class="bcw-section-sub-header">showing page <%= @page %> of <%= @max_page %></div>

    <div class="events-list">
      <% @events.each do |event| %>
        <%= render 'event_tile', :event => event %>
      <% end %>
    </div>

  </div>


</div>

app/views/home/index.html.erb
<div class="bcw-left-pane">
  <div class="home-main-tile">
    <div class="home-main-tile-header">
      Find the best in wedding planning for
    </div>
    <div class="home-main-tile-header large">
      <%= city_name_pretty %> Weddings
    </div>
    <div class="home-main-tile-text">
      Discover Washington DC wedding planning ideas for your DC wedding. Search newlywed reviews for highly rated Washington DC reception sites, Washington DC wedding cakes professionals, Washington DC photographers and many more. Find Washington DC bridal shows and events in addition to wedding vendors to help you plan your perfect wedding.
    </div>
  </div>
  <div class="home-main-tile-image"></div>

  <div style="clear: both"></div>

  <div class="home-categories-container">
    <div class="bcw-section-header categories-header">Top Rated <%= city_name_pretty %> Wedding Vendors</div>

    <!--Category Tiles-->
    <% @categories.each do |cat| %>
        <div class="category-tile">
          <a href="#"><div class="category-tile-image <%= cat.api_string %>"></div></a>
          <div class="category-name"><%= link_to cat.name, "#" %></div>
        </div>
    <% end %>

  </div>
</div>

app/views/layouts/_bcw_footer.html.erb
<div id="bcw-footer">
  <div class="bcw-footer-seo-text">
    <%= city_name_pretty %> Weddings - Discover highly rated <%= city_name_pretty %> wedding vendors. Find <%= city_name_pretty %> wedding planning ideas and more.
  </div>

  <div class="bcw-footer-links">
    <div class="city-landing-city-column">
      <div class="city-landing-citylist-text"><a href="http://www.thebestatlantaweddings.com" target="_blank">Atlanta Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestbaltimorewedding.com" target="_blank">Baltimore Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestbostonweddings.com" target="_blank">Boston Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.thebestchicagoweddings.com" target="_blank">Chicago Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestdallasweddings.com" target="_blank">Dallas Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestdenverweddings.com" target="_blank">Denver Weddings</a></div>
    </div>

    <div class="city-landing-city-column">
      <div class="city-landing-citylist-text"><a href="http://www.bestdetroitweddings.com" target="_blank">Detroit Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.besthoustonweddings.com" target="_blank">Houston Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.thebestlasvegasweddings.com" target="_blank">Las Vegas Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestlongislandweddings.com" target="_blank">Long Island Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestlosangelesweddings.com" target="_blank">Los Angeles Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.thebestmiamiweddings.com" target="_blank">Miami Weddings</a></div>
    </div>

    <div class="city-landing-city-column">
      <div class="city-landing-citylist-text"><a href="http://www.bestminneapolisweddings.com" target="_blank">Minneapolis Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestmanhattanweddings.com" target="_blank">New York City Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestocweddings.com" target="_blank">Orange County Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestorlandoweddings.com" target="_blank">Orlando Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestphiladelphiaweddings.com" target="_blank">Philadelphia Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestphoenixweddings.com" target="_blank">Phoenix Weddings</a></div>
    </div>

    <div class="city-landing-city-column">
      <div class="city-landing-citylist-text"><a href="http://www.bestraleighweddings.com" target="_blank">Raleigh Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestsandiegoweddings.com" target="_blank">San Diego Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestsanfranciscoweddings.com" target="_blank">San Francisco Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestseattleweddings.com" target="_blank">Seattle Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.besttampaweddings.com" target="_blank">Tampa Weddings</a></div>
      <div class="city-landing-citylist-text"><a href="http://www.bestdcweddings.com" target="_blank">Washington, DC Weddings</a></div>
    </div>
  </div>

</div>

app/views/layouts/_bcw_header.html.erb
<div class="city-landing-header">
  <div class="site-center">
    <a href="#"><span class="city-landing-logo <%= @bcw_city[:url_slug] %>"></span></a>
    <a href="#"><span class="city-landing-bcw-logo"></span></a>
  </div>
</div>

<div style="clear:both"></div>
<div class="site-navigation-bar-container">

  <div class="site-navigation-bar-inner">
    <%= link_to "Home", root_path, :class => "site-navigation-bar-button left site-navigation-bar-highlighted" %>
    <%= link_to "Wedding Vendors", vendors_landing_path(:city_seo_string => "washington-dc"), :class => "site-navigation-bar-button site-navigation-bar-highlighted" %>
    <%= link_to "Real Reviews", root_path, :class => "site-navigation-bar-button site-navigation-bar-highlighted" %>
    <%= link_to "Local Events", events_path(:city_seo_string => "washington-dc"), :class => "site-navigation-bar-button site-navigation-bar-highlighted" %>
    <%= link_to "Other Editions", root_path, :class => "site-navigation-bar-button site-navigation-bar-highlighted" %>
  </div>

</div>

<%= content_for :scripts do %>
    <script type="text/javascript">
      $(function(){
          $('.site-navigation-bar-button').hover(
                  function(){
                      $(this).css({
                          backgroundColor: '#ffe3ec',
                          textDecoration: 'none',
                          color: '#444'
                      });
                  },
                  function(){
                      $(this).css({
                          backgroundColor: '#FFFFFF',
                          textDecoration: 'none',
                          color: '#444'
                      });
                  });
      });
    </script>

<% end %>

app/views/layouts/_bcw_sidebar.html.erb
<div class="bcw-right-pane">

  <%= render 'layouts/recently_reviewed_tile' %>

  <%= render 'layouts/bridal_shows_tile' %>

  <div class="sidebar-pane">
    <div class="sidebar-vendor-badge">
      <%= image_tag 'BCW-vendorbadge.gif' %>
    </div>
    <div class="sidebar-vendor-badge-code">
      <div class="badge-code-header">WEDDING PROFESSIONALS!</div>
      Embed this on your website using the code below:
      <%= text_area_tag 'embed-code', '<a href = "http://www.bestdcweddings.com" alt="Washington, DC weddings"><img src = "http://bestdcweddings.com/wwsites/code/images/common/BCW-vendorbadge.gif"/></a>', :class => "badge-code-container" %>
    </div>
  </div>

</div>

app/views/layouts/_bridal_shows_tile.html.erb
<div class="sidebar-pane">
  <div class="bcw-section-header">
    <%= city_name_pretty %> Bridal Shows
  </div>

  <% @sidebar_events.each do |event| %>
    <div class="content-row">
      <div class="event-date"><%= event.start_date.strftime("%b %-1d") %></div>

      <div class="event-description">
        <div class="event-title"><%= event.title %></div>
        <div class="event-host core-ellipsis"><span class="light">Hosted By: </span><%= event.vendor.name %></div>
      </div>
    </div>
  <% end %>

  <div class="more-link">
    <%= link_to "&raquo; more events in #{city_name_pretty.downcase}".html_safe, "#" %>
  </div>
</div>

app/views/layouts/_recently_reviewed_tile.html.erb
<div class="sidebar-pane">
    <div class="bcw-section-header">
      Recently Reviewed Vendors
    </div>

    <div class="header-row">
      <div class="vendor">Vendor</div>
      <div class="review">Last Review</div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BCW</title>
  <%= stylesheet_link_tag    "application", params[:controller], :media => "all" %>
  <%= javascript_include_tag "application", params[:controller] %>

  <link rel="icon" type="image/ico" href="<%= image_path "favicon.ico" %>"/>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body id="<%= params[:controller] %>-<%= params[:action] %>">

    <%= render "layouts/bcw_header" %>

    <div id="bcw-content">
        <%= yield %>

        <%= render "layouts/bcw_sidebar" %>
    </div>

    <div style="clear:both"></div>

    <%= render "layouts/bcw_footer" %>

    <%= yield :scripts %>

</body>
</html>